# docker-compose.prod.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env      # your DATABASE_URL, REDIS_URL, etc.
    ports:
      - "8000:8000"         # maps container’s 8000 → host’s 8000
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
      
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ereader
      POSTGRES_PASSWORD: ereaderpass
      POSTGRES_DB: ereader
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"             # maps container’s 80 → host’s 80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
