# docker-compose.yml
version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env.dev:/app/.env.dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
      - redis
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "yarn install && yarn dev --host 0.0.0.0"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
