# docker-compose.yml
version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "yarn install && yarn dev --host 0.0.0.0"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-dev/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ereader
      POSTGRES_PASSWORD: ereaderpass
      POSTGRES_DB: ereader
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
