# docker-compose.yml
version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev --host 0.0.0.0

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ereader
      POSTGRES_PASSWORD: ereaderpass
      POSTGRES_DB: ereader
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --save ""  # run without persistence for caching
    ports:
      - "6379:6379"

volumes:
  db-data:
