# docker-compose.prod.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env      # your DATABASE_URL, REDIS_URL, etc.
    ports:
      - "8000:8000"         # maps container’s 8000 → host’s 8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"             # maps container’s 80 → host’s 80
    depends_on:
      - backend
    restart: unless-stopped
