# docker-compose.prod.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: ereader-backend:latest
    env_file:
      - ./backend/.env      # your DATABASE_URL, REDIS_URL, etc.
      - REDIS_URL: unix://redis:6379
    ports:
      - "8000:8000"         # maps container’s 8000 → host’s 8000
    restart: unless-stopped
    depends_on:
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ereader
      POSTGRES_PASSWORD: ereaderpass
      POSTGRES_DB: ereader
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod            # maps container’s 80 → host’s 80
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
