[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio==4.9.0",
    "bcrypt==4.3.0",
    "click==8.1.8",
    "ebooklib==0.18",
    "ecdsa==0.19.1",
    "fastapi==0.95.2",
    "greenlet==3.2.2",
    "h11==0.16.0",
    "httptools==0.6.4",
    "idna==3.10",
    "lxml==5.4.0",
    "passlib==1.7.4",
    "psycopg2-binary==2.9.7",
    "pyasn1==0.6.1",
    "pydantic==1.10.22",
    "python-dotenv==1.1.0",
    "python-jose==3.3.0",
    "python-multipart==0.0.6",
    "pyyaml==6.0.2",
    "redis==4.5.4",
    "rsa==4.9.1",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.38",
    "starlette==0.27.0",
    "typing-extensions==4.13.2",
    "uvicorn==0.22.0",
    "uvloop==0.21.0",
    "watchfiles==1.0.5",
    "websockets==15.0.1",
]
